SET IDENTITY_INSERT [dbo].[CategoriesP] ON
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (1, N'Arts')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (2, N'Culture')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (3, N'Events')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (4, N'Geography')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (5, N'Health')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (6, N'History')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (7, N'Humanities')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (8, N'Matter')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (9, N'Nature')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (10, N'People')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (11, N'Philosophy')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (12, N'Politics')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (13, N'Religion')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (14, N'Science and technology')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (15, N'Society')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (16, N'Sports')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (17, N'Universe')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (18, N'World')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (19, N'Mathematics')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (20, N'Tennis')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (21, N'Spain')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (28, N'Daylight saving time')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (29, N'Life')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (30, N'South Africa')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (31, N'Kobe Bryant')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (32, N'Switzerland')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (33, N'Television show')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (34, N'Football')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (35, N'Fashion')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (36, N'Taxonomy (biology)')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (37, N'Roman Empire')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (38, N'Music')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (39, N'PRS Guitars')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (40, N'Fighter jet')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (41, N'Iron Man (2008 film)')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (42, N'Business')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (43, N'Japan')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (44, N'Saudi Arabia')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (45, N'Germany')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (46, N'Greek mythology')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (47, N'Facebook')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (48, N'Animal')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (49, N'Arabs')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (50, N'Arabic')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (51, N'Arab world')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (52, N'Messi')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (53, N'Myanmar')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (54, N'Interior design')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (55, N'Animals')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (56, N'asd')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (57, N'DS2')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (58, N'sddd')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (59, N'Horse racing')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (60, N'Computer')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (61, N'Software')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (62, N'Programming')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (63, N'Computer science')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (64, N'Programming language')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (65, N'gfufvjhvhj')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (66, N'Big data')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (67, N'Traveling')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (68, N'Industry 4.0')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (69, N'TV shows')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (70, N'Movies')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (71, N'')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (72, N'Israel')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (73, N'Kids television channel')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (74, N'Sci &amp; Tech')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (75, N'Bible')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (76, N'JavaScript')
INSERT INTO [dbo].[CategoriesP] ([CategoryId], [CategoryName]) VALUES (77, N'Software engineering')
SET IDENTITY_INSERT [dbo].[CategoriesP] OFF
